# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=2083)),
                ('short', models.CharField(max_length=50)),
            ],
        ),
    ]
