# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(max_length=500),
        ),
    ]
