# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20160302_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original',
            field=models.URLField(max_length=2083),
        ),
    ]
