# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
